name: mss301-shared
services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD -D order_service -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
