spring.application.name=inventory-service
server.port=${SERVER_PORT:8082}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inventory_service}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
